const REVIEW_TEXT_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\bcharacterProfiles\b/g, "人物档案"],
  [/\bcharacter_profiles\b/g, "人物档案"],
  [/\bcharacter profiles\b/gi, "人物档案"],
  [/\bcharacters\b/g, "人物档案"],
  [/\bcharacter\b/g, "人物"],
  [/\btaskCardId\b/g, "任务卡编号"],
  [/\btaskCard\b/g, "章节任务卡"],
  [/\btask_card\b/g, "章节任务卡"],
  [/\btask card\b/gi, "章节任务卡"],
  [/\brequiredCharacters\b/g, "任务卡指定出场人物"],
  [/\brequired_characters\b/g, "任务卡指定出场人物"],
  [/\brequired characters\b/gi, "任务卡指定出场人物"],
  [/\bplotState\b/g, "主线状态"],
  [/\bplot_state\b/g, "主线状态"],
  [/\bplot state\b/gi, "主线状态"],
  [/\bwriting bible\b/gi, "创作圣经"],
  [/\bstory bible\b/gi, "创作圣经"],
  [/\bbible\b/gi, "创作圣经"],
  [/\bforeshadowings\b/g, "伏笔表"],
  [/\bforeshadowing\b/g, "伏笔"],
  [/\bchapterLedger\b/g, "章节台账"],
  [/\bchapter_ledger\b/g, "章节台账"],
  [/\bchapter ledger\b/gi, "章节台账"],
  [/\bledger\b/g, "章节台账"],
  [/\breviewReport\b/g, "审稿报告"],
  [/\breview_report\b/g, "审稿报告"],
  [/\breview report\b/gi, "审稿报告"],
  [/\bdraftId\b/g, "正文编号"],
  [/\bdraft_id\b/g, "正文编号"],
  [/\bdraft\b/g, "正文草稿"],
  [/\breview\b/g, "审稿"],
  [/\bcontinuity\b/g, "承接前文"],
  [/\breader hook\b/gi, "读者钩子"],
  [/\bcliffhanger\b/g, "章末钩子"],
  [/\bpayoff\b/g, "爽点回报"],
  [/\bpacing\b/g, "节奏"],
  [/\bstyle\b/g, "风格"],
  [/\bprose\b/g, "行文"],
  [/\bworldbuilding\b/g, "世界观设定"],
  [/\bpowerSystem\b/g, "战力体系"],
  [/\bpower_system\b/g, "战力体系"],
  [/\bpower system\b/gi, "战力体系"],
  [/\bgoldenFingerRules\b/g, "金手指规则"],
  [/\bgolden_finger_rules\b/g, "金手指规则"],
  [/\bgolden finger rules\b/gi, "金手指规则"],
  [/\bknownInformation\b/g, "已知信息"],
  [/\bknown_information\b/g, "已知信息"],
  [/\bknown information\b/gi, "已知信息"],
  [/\bunknownInformation\b/g, "未知信息"],
  [/\bunknown_information\b/g, "未知信息"],
  [/\bunknown information\b/gi, "未知信息"],
  [/\bcurrentState\b/g, "当前状态"],
  [/\bcurrent_state\b/g, "当前状态"],
  [/\bcurrent state\b/gi, "当前状态"],
  [/\bcurrentGoal\b/g, "当前目标"],
  [/\bcurrent_goal\b/g, "当前目标"],
  [/\bcurrent goal\b/gi, "当前目标"],
  [/\brulesNotToBreak\b/g, "不可违反设定"],
  [/\brules_not_to_break\b/g, "不可违反设定"],
  [/\brules not to break\b/gi, "不可违反设定"],
  [/\bentityRelations\b/g, "人物关系"]
];

export function formatReviewText(value?: string | null) {
  return REVIEW_TEXT_REPLACEMENTS.reduce(
    (text, [pattern, replacement]) => text.replace(pattern, replacement),
    String(value ?? "")
  ).trim();
}
