CREATE TABLE IF NOT EXISTS "AppState" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "payload" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
